/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AddictionsIndexRouteImport } from './routes/addictions.index'
import { Route as AddictionsSlugRouteImport } from './routes/addictions.$slug'
import { Route as StoriesIndexRouteImport } from './routes/stories.index'
import { Route as StoriesKeyRouteImport } from './routes/stories.$key'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AddictionsIndexRoute = AddictionsIndexRouteImport.update({
  id: '/addictions/',
  path: '/addictions/',
  getParentRoute: () => rootRouteImport,
} as any)
const AddictionsSlugRoute = AddictionsSlugRouteImport.update({
  id: '/addictions/$slug',
  path: '/addictions/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesIndexRoute = StoriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StoriesRoute,
} as any)
const StoriesKeyRoute = StoriesKeyRouteImport.update({
  id: '/$key',
  path: '/$key',
  getParentRoute: () => StoriesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/addictions/$slug': typeof AddictionsSlugRoute
  '/stories/$key': typeof StoriesKeyRoute
  '/addictions/': typeof AddictionsIndexRoute
  '/stories/': typeof StoriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/addictions/$slug': typeof AddictionsSlugRoute
  '/stories/$key': typeof StoriesKeyRoute
  '/addictions': typeof AddictionsIndexRoute
  '/stories': typeof StoriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/addictions/$slug': typeof AddictionsSlugRoute
  '/stories/$key': typeof StoriesKeyRoute
  '/addictions/': typeof AddictionsIndexRoute
  '/stories/': typeof StoriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/addictions/$slug'
    | '/stories/$key'
    | '/addictions/'
    | '/stories/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/addictions/$slug'
    | '/stories/$key'
    | '/addictions'
    | '/stories'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/addictions/$slug'
    | '/stories/$key'
    | '/addictions/'
    | '/stories/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  AddictionsSlugRoute: typeof AddictionsSlugRoute
  AddictionsIndexRoute: typeof AddictionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/addictions/': {
      id: '/addictions/'
      path: '/addictions'
      fullPath: '/addictions/'
      preLoaderRoute: typeof AddictionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/addictions/$slug': {
      id: '/addictions/$slug'
      path: '/addictions/$slug'
      fullPath: '/addictions/$slug'
      preLoaderRoute: typeof AddictionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/': {
      id: '/stories/'
      path: '/'
      fullPath: '/stories/'
      preLoaderRoute: typeof StoriesIndexRouteImport
      parentRoute: typeof StoriesRoute
    }
    '/stories/$key': {
      id: '/stories/$key'
      path: '/$key'
      fullPath: '/stories/$key'
      preLoaderRoute: typeof StoriesKeyRouteImport
      parentRoute: typeof StoriesRoute
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  AddictionsSlugRoute: AddictionsSlugRoute,
  AddictionsIndexRoute: AddictionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
